[versions]
mariadb = "3.5.0"
kaml = "0.67.0"

# Run server versions
paper-server = "1.21.4"
commandapi-server = "9.7.0"

[libraries]
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
kaml = { module = "com.charleskorn.kaml:kaml-jvm", version.ref = "kaml" }